server:
  port: 8092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin1998
    url: jdbc:postgresql://127.0.0.1:5432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource

  ai:
    dashscope:
      api-key: sk-762e6e532c8a4745b881bbf2a7db7608
      chat:
        options:
          model: qwen3-max
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/config/ mcp-servers-config.json

# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
